name: eval-framework
services:
  db:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant_storage:/qdrant/storage
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - 8000:8000
    
  